convert to python3
jimrollenhagen/pywhatauto pull request #44
Opened 2017-05-09 09:22 UTC by gnowxilef

- update with new irclib
- run 2to3 conversion on python files

2017-05-09 09:22 UTC, gnowxilef commented
fixes https://github.com/jimrollenhagen/pywhatauto/issues/43

2017-06-01 21:59 UTC, jimrollenhagen requested changes
Thanks for doing this, it's much appreciated :)

There's lots of things to clean up here, noted some of them inline. This also doesn't work on python 2, which I think we should still support.

2017-06-01 21:59 UTC, jimrollenhagen commented on globals.py
> +import threading, sys, os, queue#, thread
This won't work on python 2, we should support both. We could use six (https://pythonhosted.org/six/) to do this, however that would be a new external dependency, which we don't tend to place on users (though I'm open to changing things up to do this).

Alternatively, could try/except ImportError to do the right thing.

2017-06-01 21:59 UTC, jimrollenhagen commented on irclib.py
> +# Copyright (C) 1999--2002 Joel Rosdahl
No need to change whitespace, just makes the diff harder to review, and breaks the blame.

2017-06-01 21:59 UTC, jimrollenhagen commented on irclib.py
> +"""
Ditto re: whitespace, and all through this file. Python style convention is the way this was before.

2017-06-01 21:59 UTC, jimrollenhagen commented on irclib.py
> +        sockets = [x for x in sockets if x != None]
Why change this?

2017-06-01 21:59 UTC, jimrollenhagen commented on irclib.py
> +            (i, o, e) = select.select(sockets, [], [], timeout)
Ditto, no need to change this

2017-06-01 21:59 UTC, jimrollenhagen commented on irclib.py
> +sslsock -- Enable support for ssl.
Now I'm wondering, did you just pull a new version of irclib.py? If so, that's fine, but please note that in the commit message and/or pull request description.

2017-06-01 21:59 UTC, jimrollenhagen commented on torrentparser.py
> +    print(('%-50s %-3s %10.2s  %-5s' %('Infohash','M','MBs','Name')))
No need for double parens here (and other places in the diff)

2017-06-01 21:59 UTC, jimrollenhagen commented on torrentparser.py
> -from __future__ import division
Might still need this on 2.x?

2017-06-01 21:59 UTC, jimrollenhagen commented on torrentparser.py
> +        for key in sorted(iter(dictionary.keys()),key=str.lower):
Should just be able to do `dictionary.keys()` here, iirc

2017-06-01 21:59 UTC, jimrollenhagen commented on WHATauto.py
> +from socketserver import ThreadingMixIn
Same problems here as below with imports

2017-06-01 21:59 UTC, jimrollenhagen commented on WHATauto.py
> +import db, time, os, re, configparser, _thread, urllib.request, urllib.parse, urllib.error, urllib.request, urllib.error, urllib.parse, random, http.cookiejar, socket, math, traceback, sqlite3, ssl,
Same import issue

2017-06-01 21:59 UTC, jimrollenhagen commented on WHATauto.py
> +    for val in list(G.TOALIAS.values()):
no need for `list()`

2017-06-17 00:08 UTC, gnowxilef commented on irclib.py
> +# Copyright (C) 1999--2002 Joel Rosdahl
huh, i wonder how that got changed.

2017-06-17 00:10 UTC, gnowxilef commented on irclib.py
> +        sockets = [x for x in sockets if x != None]
`2to3` automagically changed it if i am not mistaken.

2017-06-17 00:10 UTC, gnowxilef commented on irclib.py
> +            (i, o, e) = select.select(sockets, [], [], timeout)
`2to3` automagically changed it if i am not mistaken.

2017-06-17 00:11 UTC, gnowxilef commented on irclib.py
> +sslsock -- Enable support for ssl.
yeah i did. if i didn't, the program failed to load correctly.

2017-06-17 00:11 UTC, gnowxilef commented on torrentparser.py
> +    print(('%-50s %-3s %10.2s  %-5s' %('Infohash','M','MBs','Name')))
good catch.

2017-06-17 00:11 UTC, gnowxilef commented on torrentparser.py
> +        for key in sorted(iter(dictionary.keys()),key=str.lower):
`2to3` automagically changed it if i am not mistaken. i'll change it back.

2017-06-17 00:12 UTC, gnowxilef commented on WHATauto.py
> +    for val in list(G.TOALIAS.values()):
`2to3` automagically changed it if i am not mistaken. i'll change it back.

2020-05-06 01:20 UTC, closed without merging